config/routes.rb
Sharelink::Application.routes.draw do
  get "welcome/index"

  resources :links

  resources :categories
  
  root :to => "welcome#index"
  
  
  match 'welcome' => 'welcome#index'
  match 'welcome/:catid' => 'welcome#index'
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :id, :name
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :catid, :content, :gmt_created, :gmt_modified, :id, :name, :url, :view
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_charset
  def set_charset
      headers["Content-Type"] ||= "text/html; charset=utf-8" 
  end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])
    print @category.name

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET /links
  # GET /links.json
  def index
    @links = Link.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new
    @categories = Category.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
      format.json { render json: @categories }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  # GET /
  # GET /welcome/1
  # GET /welcome/1.json
  def index
    
    @catid = params[:catid]
    if @catid==nil
      @catid = 0.to_i
    else
      @catid = @catid.to_i
    end
    
    
    @pageindex = params[:pageindex].to_i
    if @pageindex==nil || @pageindex <= 1
      @pageindex = 1.to_i
    end
    if @catid > 0
      @links = Link.where("catid =?", params[:catid]).order("gmt_modified DESC, id desc").limit(2).offset((@pageindex-1)*2)
      @count = Link.where("catid =?", params[:catid]).count
    else
      @links = Link.order("gmt_modified DESC, id desc").limit(2).offset((@pageindex-1)*2)
      @count = Link.count
    end

    if @count % 2
      @totalpage = @count / 2 + 1
    else
      @totalpage = @count / 2 
    end

    @categories = Category.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories}
      format.json { render json: @links}
      format.json { render json: @count}
      format.json { render json: @totalpage}
      format.json { render json: @pageindex}
      format.json { render json: @catid}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.id %></td>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @category.id %>
</p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sharelink</title>
  <meta http-equiv="Content-type" content="text/rhtml; charset=utf8" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :gmt_created %><br />
    <%= f.datetime_select :gmt_created %>
  </div>
  <div class="field">
    <%= f.label :view %><br />
    <%= f.number_field :view %>
  </div>
  <div class="field">
    <%= f.label :gmt_modified %><br />
    <%= f.datetime_select :gmt_modified %>
  </div>
  <div class="field">
    <%= f.label :catid %><br />
    <%= f.number_field :catid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Url</th>
    <th>Content</th>
    <th>Gmt created</th>
    <th>View</th>
    <th>Gmt modified</th>
    <th>Catid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <td><%= link.id %></td>
    <td><%= link.name %></td>
    <td><%= link.url %></td>
    <td><%= link.content %></td>
    <td><%= link.gmt_created %></td>
    <td><%= link.view %></td>
    <td><%= link.gmt_modified %></td>
    <td><%= link.catid %></td>
    <td><%= link_to 'Show', link %></td>
    <td><%= link_to 'Edit', edit_link_path(link) %></td>
    <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @link.id %>
</p>

<p>
  <b>Name:</b>
  <%= @link.name %>
</p>

<p>
  <b>Url:</b>
  <%= @link.url %>
</p>

<p>
  <b>Content:</b>
  <%= @link.content %>
</p>

<p>
  <b>Gmt created:</b>
  <%= @link.gmt_created %>
</p>

<p>
  <b>View:</b>
  <%= @link.view %>
</p>

<p>
  <b>Gmt modified:</b>
  <%= @link.gmt_modified %>
</p>

<p>
  <b>Catid:</b>
  <%= @link.catid %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/welcome/index.html.erb
<div class="layout">
	<h1>极客头条</h1>
	
	<table class="category">
	  <tr>
	  	<td class="catitem">分类列表：</td>
	  	<td class="catitem"><a href="/">All</a></td>
	  	<% @categories.each do |category| %>
	    <td class="catitem <% if category.id.to_i == @catid %> selected <% end %>"><a href="/welcome/<%= category.id %>"><%= category.name %></a></td>
	    <% end %>
	  </tr>
	</table>

	<br />
	
	<ul class="linklist">
		<% @links.each do |link| %>
		<li>
			<div class="title"><a href="<%= link.url %>" target="_blank"> <%= link.name %></a><span class="time"><%= link.gmt_created.strftime("%Y-%m-%d")  %></span></div>
			<div class="content"><a href=""><%= link.content %></a></div>
		</li>
		<% end %>
	</ul>
	<div class="page">
	当前第<%= @pageindex %>页
	<% if @pageindex > 1 %><a href="/welcome/<%=@catid%>?pageindex=<%=@pageindex-1%>">上一页</a> <% else %>上一页<% end %>
	<% if @totalpage > @pageindex %><a href="/welcome/<%=@catid%>?pageindex=<%=@pageindex+1%>">下一页</a> <% else %> 下一页 <% end %>
	总共<%= @totalpage %>页
	</div>
	<br />
</div>